# Generated by Django 5.0.2 on 2024-05-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_signup_username_signup_address_signup_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
