# Generated by Django 5.0.2 on 2024-05-08 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_signup_is_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='signup',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='signup',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
