# Generated by Django 5.0.6 on 2024-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0009_rename_image_doctorprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
