# Generated by Django 5.0.2 on 2024-05-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_signup_username_signup_address_signup_age_and_more'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_signup',
            name='doctor',
            field=models.ForeignKey(default='no_doctor', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile'),
        ),
    ]
