# Generated by Django 5.0.2 on 2024-05-21 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_signup_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventricular_rate', models.FloatField(blank=True, null=True)),
                ('atrial_rate', models.FloatField(blank=True, null=True)),
                ('qrs_duration', models.FloatField(blank=True, null=True)),
                ('qt_interval', models.FloatField(blank=True, null=True)),
                ('qt_corrected', models.FloatField(blank=True, null=True)),
                ('r_axis', models.FloatField(blank=True, null=True)),
                ('t_axis', models.FloatField(blank=True, null=True)),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data', to='patient.patient_signup')),
            ],
        ),
    ]
