# Generated by Django 5.0.2 on 2024-05-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patientmedicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicaldata',
            name='q_offset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicaldata',
            name='q_onset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicaldata',
            name='qrs_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicaldata',
            name='t_offset',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
