# Generated by Django 5.0.6 on 2024-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0005_patientmedicaldata_q_offset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient_signup",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
