# Generated by Django 5.0.6 on 2024-07-04 15:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0007_ecgreading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ecgreading",
            name="value",
        ),
        migrations.AddField(
            model_name="ecgreading",
            name="values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), null=True, size=1000
            ),
        ),
    ]
