# Generated by Django 5.0.6 on 2024-07-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0008_remove_ecgreading_value_ecgreading_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientmedicaldata",
            name="q_offset",
        ),
        migrations.RemoveField(
            model_name="patientmedicaldata",
            name="q_onset",
        ),
    ]
